
Exception handling :
----------------------------------------------
Exception :
->when make code and disrupts normal flow of the program . 

----------------------------------------------------
types :
->check Exception 
->unchecked exception 

->check Exception 
	compile time exception 

->unchecked exception 
	runtime exception 
----------------------------------------------------
Exception handling mechanism : 
->it is used to handle the exceptions 

try 
catch 
finally 
throw 
throws 
----------------------------------------------------
try block :
->it is keyword 
->it is used to write a code 
->try always with catch 
->try always with finally 
->try catch finally 

syntax :
try{

}
----------------------------------------------------
catch block : 
->it is keyword 
->it is used to handle the exception 
->try catch 
->try catch finally 

syntax:
try{

}
catch(exception){

}
----------------------------------------------------
arithmetic exception : 
->when number is divide by zero 

ArithemticException1.java
public class ArithemticException1{
    public static void main(String[] args) {
        int a=7;
        int b=0;
        int c=a/b;
        System.out.println(c);
    }
}
-------------------------------------------
want to handle the excpetion : 
try -->catch 

ArithException.java
public class ArithemticException1 {
    public static void main(String[] args) {
        try {
            int a = 7;
            int b = 0;
            int c = a / b;
            System.out.println(c);
        }
        // ArithemticException class refrence variable
        catch (ArithmeticException ex) {
            System.out.println("exception handle");
        }
    }
}
------------------------------------------------
finally :
->it is also block 
->it always executed 

try--->finally 
public class ArithemticException1 {
    public static void main(String[] args) {
        try {
            int a = 10;
            int b = 0;
            System.out.println(a / b);
        } finally {
            System.out.println("always executed");
        }
    }
}
-----------------------------------------
try --->catch-->finally 
public class ArithemticException1 {
    public static void main(String[] args) {
        try {
            int a = 10;
            int b = 0;
            System.out.println(a / b);
        } catch (ArithmeticException ex) {v
            System.out.println("Exception Handle");
        } finally {
            System.out.println("always executed");
        }
    }
}








